const list = [
    {
        id: "aORb",
        input: [
            [Array],
            [Array],
            [Array],
            [Array],
            [Array],
            [Array],
            [Array],
            [Array],
            [Array],
            [Array],
            [Array],
            [Array],
            [Array],
            [Array],
            [Array],
            [Array],
        ],
        output: [0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1],
    },
    "AND",
    {
        id: "a",
        input: [
            [Array],
            [Array],
            [Array],
            [Array],
            [Array],
            [Array],
            [Array],
            [Array],
            [Array],
            [Array],
            [Array],
            [Array],
            [Array],
            [Array],
            [Array],
            [Array],
        ],
        output: [0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
    },
    "OR",
    "(",
    {
        id: "c",
        input: [
            [Array],
            [Array],
            [Array],
            [Array],
            [Array],
            [Array],
            [Array],
            [Array],
            [Array],
            [Array],
            [Array],
            [Array],
            [Array],
            [Array],
            [Array],
            [Array],
        ],
        output: [0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1],
    },
    "OR",
    {
        id: "d",
        input: [
            [Array],
            [Array],
            [Array],
            [Array],
            [Array],
            [Array],
            [Array],
            [Array],
            [Array],
            [Array],
            [Array],
            [Array],
            [Array],
            [Array],
            [Array],
            [Array],
        ],
        output: [0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1],
    },
    ")",
    "AND",
    {
        id: "b",
        input: [
            [Array],
            [Array],
            [Array],
            [Array],
            [Array],
            [Array],
            [Array],
            [Array],
            [Array],
            [Array],
            [Array],
            [Array],
            [Array],
            [Array],
            [Array],
            [Array],
        ],
        output: [0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1],
    },
]

console.log(list.slice(4, 9))
